### ISSUE TITLE
使用find功能只能搜索主目录下的文件

### ISSUE THREAD

**Issue by zed7th** [zaaack/ELaunch#14]
使用find查找文件时只能查找到/home路径下的文件，updatedb已经给了权限，请问我想要查找其他路径比如/usr或者/etc路径下的文件应该怎么做

**Comment by zaaack** [comment]
可以修改 `~/.Elaunch/config.json5` 里 find 插件配置， rootDir: '~' 改为 rootDir: '/', 不过可能会造成索引目录过多的问题。。

**Comment by zed7th** [comment]
谢谢大佬，修改过后可以了，启动器很实用，就是不支持快速打开文件所在的路径有点遗憾

**Comment by zaaack** [comment]
很久没维护了。。
