### ISSUE TITLE
在Deepin上无法快捷键呼出启动器

### ISSUE THREAD

**Issue by wangzk** [zaaack/ELaunch#3]
我用的是Deepin Linux 15.2， 但是我无法使用快捷键"Super+Space"呼出启动器。不知道是什么缘故？
我直接在托盘图表上右键启动是可以用的。

**Comment by zaaack** [comment]
可能是快捷键冲突，可以在config.js里修改快捷键，注意不同版本的格式可能有所不同，具体请看你用的版本的config.default.js
