### ISSUE TITLE
there is a bug in dual monitor display 

### ISSUE THREAD

**Issue by Powerful24HS** [zaaack/ELaunch#4]
双显示器，快捷命令栏的输入框在中间，希望能调整到主显示器的中心位置。
我看了源码，设定 config.width 没有用。

**Comment by zaaack** [comment]
@Powerful24HS 这是electron的bug， 刚才增加了位置(x, y)的手动配置。设定没有作用可能需要重启 。github发布上传很慢，临时手动打包了一下最新的： https://pan.baidu.com/s/1qXDQGLA
