### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by wayne0332** [zaaack/ELaunch#5]
你好,我根据使用文档里的[Develop]那节,自己把源码下载下来,然后用npm安装  
在执行完npm start后,按cmd+space没有弹出搜索框  
## 我的系统是osx10.11.6,请问一下这个哪里可以看到相关日志,可以知道是哪里出了问题吗

最新观察是打开的时候闪退了

**Comment by zaaack** [comment]
@wayne0332  把进程杀死，然后再重新运行`npm start` ，或者运行 `npm run debug` 试试，如果报错的话一般命令行会显示错误

**Comment by zaaack** [comment]
也不排除是快捷键冲突，可以试试任务栏菜单的toggle

**Comment by wayne0332** [comment]
找到问题了 app/index.js这个文件里算窗口Position的时候 如果参数是个float 就会什么都不显示
把float转成int就可以了
![image](https://cloud.githubusercontent.com/assets/5112427/18261873/1586f07e-742f-11e6-95c0-867f027ab66f.png)

**Comment by wayne0332** [comment]
另外mac系统下算app索引的时候 如果Contents/Info.plist是二进制的而不是xml的 会解析出错
用plutil -p file命令貌似可以直接打印文件内容 不管这玩意是什么格式(以下代码未跑通 仅供参考)
![image](https://cloud.githubusercontent.com/assets/5112427/18261920/741be9c8-742f-11e6-9f54-b073048b25ae.png)

**Comment by wayne0332** [comment]
另外能不能给个联系方式 我本身不是搞前端的 一些js,nodejs的东西不是很懂 可能有些问题想请教一下
既然有这个开源的就不想买alfred了 有需求自己搞得了

**Comment by zaaack** [comment]
@wayne0332 你可以把联系方式发我邮箱里面

**Comment by zaaack** [comment]
@wayne0332  ps, 修改的代码可以提交pr : )

**Comment by wayne0332** [comment]
嗯 我知道 目前没弄好 所以只是提一下 弄好了在提

**Comment by zaaack** [comment]
@wayne0332 建议不要用 plutil， 我在网上搜了下，
PlistBuddy 可以直接打印出属性值
`/usr/libexec/PlistBuddy /Applications/360云盘.app/Contents/Info.plist -c 'Print :CFBundleDisplayName'`

http://blog.eexit.net/osx-dealing-with-property-list-files/

**Comment by wayne0332** [comment]
@zaaack 好的 我用PlistBuddy改一下
PlistBuddy相比plutil 的好处只是可以直接拿到想要的属性而已是吧 plutil要装mac的开发者工具集 不知道PlistBuddy要不要装
