### ISSUE TITLE
ubuntu16.04 下快捷键无相应

### ISSUE THREAD

**Issue by stormeyes** [zaaack/ELaunch#8]
配置文件如下：
module.exports = {
  position: 'center', // 'center' or {x: 100, y:200}
  shortcut: {
    toggle: {
      default: 'Ctrl+D',
      win32: 'Ctrl+D',
      linux: 'Ctrl+D',
      darwin: 'Ctrl+D'
    }
  },
  plugins: {
    // app: {
    //   path: `${__dirname}/../plugins/app/index.js`,
    //   default: true,
    //   config: {}
    // },
    find: {
      // path: `${__dirname}/../plugins/find/index.js`,
      config: {
      }
    }
  }
}

按下ctrl+D无响应， 检查后发现该快捷键并没有被别的软件占用。之前默认的super+space也无效

**Comment by zaaack** [comment]
你把shortcut 换成shotcut试试，之前我打错字了。。还有多换几个快捷键，修改完配置文件后要重启。。

**Comment by stormeyes** [comment]
@zaaack 还真是。。。。。。。。。。
